# Generated by Django 5.0.3 on 2024-03-20 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beneficiario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(max_length=11, unique=True)),
                ('pis', models.CharField(max_length=11, unique=True)),
                ('nome', models.CharField(max_length=100)),
                ('nome_pai', models.CharField(blank=True, max_length=100, null=True)),
                ('nome_mae', models.CharField(blank=True, max_length=100, null=True)),
                ('quantidade_filhos', models.PositiveIntegerField(default=0)),
                ('email', models.EmailField(max_length=254)),
                ('identidade', models.CharField(max_length=20, unique=True)),
                ('comprovante_de_residencia', models.CharField(max_length=100)),
                ('numero_carteira_trabalho', models.CharField(max_length=20, unique=True)),
            ],
        ),
    ]
