# Generated by Django 5.0.3 on 2024-03-20 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_beneficiario_identidade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiario',
            name='data_nascimento',
            field=models.DateField(null=True),
        ),
    ]
